In [1]:
import numpy as np
import pandas as pd
im
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [6]:
data = pd.read_csv('data/car data.csv')
df = pd.DataFrame(data)
df = df.drop(['Car_Name'], axis=1)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [8]:
print(df['Fuel_Type'].value_counts())

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [10]:
print(df.groupby('Fuel_Type')['Selling_Price'].mean())

Fuel_Type
CNG        3.100000
Diesel    10.278500
Petrol     3.264184
Name: Selling_Price, dtype: float64

In [ ]:
plt

In [5]:
df = pd.get_dummies(df, columns=['Fuel_Type', 'Seller_Type'], drop_first=True, dtype=int)
df['Transmission'] = df['Transmission'].map({'Manual': 0, 'Automatic': 1})
df

,Year,Selling_Price,Present_Price,Kms_Driven,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual
0,2014,3.35,5.59,27000,0,0,0,1,0
1,2013,4.75,9.54,43000,0,0,1,0,0
2,2017,7.25,9.85,6900,0,0,0,1,0
3,2011,2.85,4.15,5200,0,0,0,1,0
4,2014,4.60,6.87,42450,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,0,1,0,0
297,2015,4.00,5.90,60000,0,0,0,1,0
298,2009,3.35,11.00,87934,0,0,0,1,0
299,2017,11.50,12.50,9000,0,0,1,0,0
300,2016,5.30,5.90,5464,0,0,0,1,0